GET https://e-pharmacy-react.herokuapp.com/product-api/getproducts

###
GET https://e-pharmacy-react.herokuapp.com/product-api/getproduct/Coldarin

###
DELETE https://e-pharmacy-react.herokuapp.com/product-api/remove-product/6

